version: 2.1

# orbs:
#   maven: circleci/maven@0.0.12

jobs:
  test_env:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: show environment
          command: |
            which java
            java -version
            which mvn
            mvn --version
      
      - run:
          name: mvn install
          command: |
            mvn install

      - run:
          name: Download Snyk
          command: |
            latest_version=$(curl -Is "https://github.com/snyk/snyk/releases/latest" | grep "Location" | sed s#.*tag/##g | tr -d "\r")
            snyk_cli_dl_linux="https://github.com/snyk/snyk/releases/download/${latest_version}/snyk-linux"
            curl -Lo ./snyk $snyk_cli_dl_linux
            chmod +x ./snyk

      - run:
          name: Snyk test
          command: |
            ls -la
            ./snyk test

workflows:
  maven_test:
    jobs:
      - test_env
      # - maven/test # checkout, build, test, and upload test results
