version: 2.1

jobs:
  build_and_snyk_test:
    docker:
      - image: circleci/openjdk:jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: show environment
          command: |
            java -version
            mvn --version
      - run:
          name: mvn install
          command: |
            mvn install
      - run:
          name: Download Snyk
          command: |
            latest_version=$(curl -Is "https://github.com/snyk/snyk/releases/latest" | grep "Location" | sed s#.*tag/##g | tr -d "\r")
            snyk_cli_dl_linux="https://github.com/snyk/snyk/releases/download/${latest_version}/snyk-linux"
            curl -Lo ./snyk $snyk_cli_dl_linux
            chmod +x ./snyk
      - run:
          name: Snyk test
          command: |
            ./snyk test

workflows:
  maven_test:
    jobs:
      - build_and_snyk_test
